spring.application.name=springsecOAUTH2
spring.security.user.name=${SECURITY_USERNAME:amit}
spring.security.user.password=${SECURITY_PASSWORD:12345}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


#These values are overridden in SpringSecOAUTH2GitHubConfig in the beans
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23licjnbluSLEEMB8K}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:6540fce7cd467f1e51fc8199b652cc982150a4d1}

spring.security.oauth2.client.registration.facebook.client-id=${GITHUB_CLIENT_ID:974042741122392}
spring.security.oauth2.client.registration.facebook.client-secret=${GITHUB_CLIENT_SECRET:36d48c25c1767d58b3101551513d7e1e}
